### ISSUE TITLE
ImportError: cannot import name 'engine' from 'app.database' (E:\11-Projects\FastAPI-Boilerplate\app\database\__init__.py)

### ISSUE THREAD

**Issue by dannykellett** [tomasemilio/FastAPI-Boilerplate#3]
Hi

Sorry if this seems a simple fix but I get this without changing anything:

  File "E:\11-Projects\FastAPI-Boilerplate\app\__init__.py", line 6, in <module>
    from app.api.functions.middleware import add_process_time_header, lifespan
  File "E:\11-Projects\FastAPI-Boilerplate\app\api\functions\middleware.py", line 8, in <module>
    from app.database.create import create
  File "E:\11-Projects\FastAPI-Boilerplate\app\database\create.py", line 4, in <module>
    from app.database import engine
ImportError: cannot import name 'engine' from 'app.database' (E:\11-Projects\FastAPI-Boilerplate\app\database\__init__.py)
INFO:     Stopping reloader process [36892]

**Comment by tomasemilio** [comment]
@dannykellett 
Hi Danny, thank you for theobservation. I need to be a bit more verbose with that logic. Did you set in your `.env` file the corresponding 'DEV_DB_URL'. That's what is happening. I am going to add a default db_url for dev as well and avoid this issue.  Thank you!
