### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by realsbd** [tomasemilio/FastAPI-Boilerplate#8]
I am trying to login with credentials I set in my .env file for admin-dev login, but I'm getting this error. I tried to edit the config file to have the same details but I still get unauthorized error.

![image](https://github.com/user-attachments/assets/900a7bbc-e149-45ab-9b50-725a6c0fc605)

**Comment by tomasemilio** [comment]
Can you give me more context? The logs and also how you set up credentials. Remember that you set variables inside .env as "DEV_VAR" and not just "VAR"

**Comment by realsbd** [comment]
here is my .env
```
ENV_STATE=dev

DEV_ADMIN_EMAIL=abc@def.com
DEV_ADMIN_EMAIL_TOKEN=12345678
```

I think where I got it wrong is the password is set in the config file. I thought it should be in .env file

how secure is it in config instead of .env?
