### ISSUE TITLE
Issue with deployment

### ISSUE THREAD

**Issue by realsbd** [tomasemilio/FastAPI-Boilerplate#9]
I was able to get the app running and deploy it to the server, but when I open the URL in the browser, the page does not load the /docs.

I was able to run the code on my VPS, and it ran successfully. I also change the ENV to 'prod', since I will be using it the server for production.

is it possible for you to create a deployment readme for the project or maybe there's something I'm doing wrong.

**Comment by tomasemilio** [comment]
I will add deployment guidance and step-by-step in the future. For now, the scope of the project is to walk you through local deployment.
